### ISSUE TITLE
Memory Leak During Execution Resulted in System32 Folder Corruption

### ISSUE THREAD

**Issue by Esc0rtd** [astrochun/uarizona-salary-app#87]
I've experienced this memory leak issue as well, and I wanted to share my observations. It's unfortunate that this issue has caused such severe disruptions. Memory leaks can be particularly challenging to deal with, and when they lead to the corruption of critical system files like System32, it becomes even more urgent.

I've noticed that this issue seems to occur consistently under certain conditions, and it's not isolated to a specific system configuration. I've also attempted to reproduce the issue on a separate machine with similar hardware and software configurations, and it manifested there as well. 

It would be helpful if the development team could provide some insights into the potential root cause of this memory leak. It might be related to resource management within the application or a compatibility issue with the operating system. Any additional information or debugging steps that could be shared would be greatly appreciated.

In the meantime, I've had to restore my System32 folder from a backup to get my system up and running again. This has been a time-consuming process, and I hope that a fix for this issue can be implemented swiftly to prevent such incidents from happening in the future.

Please let us know if there are any updates or if you need further details to investigate this issue. Thank you for your attention to this matter.
This comment provides feedback and observations related to the issue, but it doesn't

**Comment by astrochun** [comment]
Hello, I'm sorry if you have encountered an issue, but I'm not entirely sure what you've experienced. You haven't provided much details to help reproduce it. I'm not sure what you mean "this memory leak" as this is the first I've heard of it and your message seems truncated.

Please keep in mind that this software was developed on a Mac and deployed on linux clusters. It has never been tested on Windows systems. I have no idea what versions of each dependencies you've installed. It could be any one of the dozens libraries that may have their own memory leak issues.

The development team is only one person and this project hasn't been maintained in about a year or so. It was a hobby project that I made available for others to benefit from.

The software is deployed on Render so I recommend using it if you so desire.
